options:
  enable-dashboard-addons:
    type: boolean
    default: True
    description: Deploy the Kubernetes Dashboard and Heapster addons
  dns_domain:
    type: string
    default: cluster.local
    description: The local domain for cluster dns
