options:
  version:
    type: string
    default: ""
    description: |
      This config option was deprecated in favor of the binary delivery pattern.
  dashboard:
    type: boolean
    default: True
    description: Deploy the Kubernetes Dashboard
